# Build settings
theme: minima
url: "https://mateovillamizarchaparro.github.io/"
title: Mateo Villamizar Chaparro
tagline: Santiago Mateo Villamizar Chaparro is a political scientist.
author:
  name: Mateo Villamizar Chaparro
  email: sv161@duke.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Political Science PhD candidate at Duke University. Ex UCSD and Universidad de los Andes.

show_excerpts: false # set to true to show excerpts on the homepage

# social_links:
# twitter_username: sanmavicha
# github_username: trmcdade
# linkedin_username: timothymcdade

google_analytics: G-3MVMRG3705

og_image: /assets/images/Villamizar Chaparro_NoPort.jpg

header_pages:
  - bio.md
  - publications.md
  - skills.md
  - cv.md
  - github.md

# layout: default

plugins:
  - jekyll-sitemap # construct sitemap
  - jekyll-seo-tag # helps with optimization
  # - jekyll-feed
  # - jekyll-sass-converter

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sanmavicha
    github:  sanmavicha
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: mateo-villamizar-chaparro
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
