# Build settings
theme: minima
url: "https://trmcdade.github.io/"
title: Timothy R. McDade
tagline: Tim McDade is a political economist.
author:
  name: Timothy R. McDade
  email: tim.mcdade@duke.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Quantitative political economist at Duke University with experience in the
  US and Chinese tech industry.

show_excerpts: false # set to true to show excerpts on the homepage

# social_links:
# twitter_username: trmcdade
# github_username: trmcdade
# linkedin_username: timothymcdade

google_analytics: G-EWMFHWFW20

og_image: /assets/images/portrait_web.jpg

# social:
#   type: Person
#   name: Timothy R. McDade
#   links:
#     - "https://twitter.com/trmcdade"
#     - "https://www.linkedin.com/in/timothymcdade"
#

header_pages:
  - bio.md
  # - education.md
  # - professionalexperience.md
  - publications.md
  - skills.md
  - cv.md
  - github.md

# layout: default

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-feed
  # - jekyll-sass-converter

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: trmcdade
    github:  trmcdade
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: timothymcdade
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
